version: 2.1

orbs:
  android: circleci/android@0.2.1

executors:
  android-executor:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      JVM_OPTS: "-Xmx3200m"
      ANDROID_HOME: /opt/android/sdk

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Setup Android SDK
          command: |
            sudo mkdir -p /opt/android/sdk
            sudo chown -R circleci:circleci /opt/android/sdk
            wget -q "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O android-commandline-tools.zip
            unzip -q android-commandline-tools.zip -d /opt/android/sdk/cmdline-tools
            mv /opt/android/sdk/cmdline-tools/cmdline-tools /opt/android/sdk/cmdline-tools/latest
            yes | /opt/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
            /opt/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      - run:
          name: Create local.properties
          command: echo "sdk.dir=/opt/android/sdk" > ./local.properties
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build:
    jobs:
      - build
